// src/lib/components/Skills.svelte
<script lang="ts">
    import { skills } from "../assets/icons";
    let showAllSkills = false;
</script>

<div class="flex flex-col gap-6">
    <div class="relative">
        <div
            class={`
                grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 xl:gap-10
                ${showAllSkills ? "overflow-y-scroll max-h-[500px] lg:max-h-[500px]" : "overflow-hidden max-h-[400px] lg:max-h-[400px]"}
                ${!showAllSkills ? "mask-b-from-60% mask-b-to-95% lg:mask-b-from-20% lg:mask-b-to-80%" : ""}
                transition-all duration-500
                ${showAllSkills ? "scrollbar-thin scrollbar-thumb-rounded scrollbar-thumb-gray-400 scrollbar-track-gray-100" : ""}
            `}
        >
            {#each skills as skill, index}
                <div
                    class="card bg-base-100 aspect-square shadow-sm text-center"
                >
                    <div class="card-body">
                        <div
                            class="h-full flex flex-col items-center justify-center gap-2"
                        >
                            {#if skill.color !== undefined}
                                <svelte:component
                                    this={skill.icon}
                                    color={skill.color}
                                    size={index > 7 ? 50 : 80}
                                    title={skill.alt ?? skill.title}
                                />
                            {:else}
                                <img
                                    src={skill.icon}
                                    alt={skill.alt ?? skill.title}
                                    title={skill.alt ?? skill.title}
                                    class="w-[80px] h-[80px] {index > 7
                                        ? 'w-[50px] h-[50px]'
                                        : ''}"
                                />
                            {/if}
                            <span
                                class={index > 7
                                    ? "text-sm uppercase"
                                    : "text-xl uppercase"}
                            >
                                {skill.title}
                            </span>
                        </div>
                    </div>
                </div>
            {/each}
        </div>
    </div>
    <div class="text-center">
        <button
            class="btn btn-ghost text-lg uppercase"
            on:click={() => (showAllSkills = !showAllSkills)}
        >
            <span
                >{showAllSkills ? "Show Less Skills" : "Show More Skills"}</span
            >
        </button>
    </div>
</div>

// src/components/Skills.tsx
import React, { useEffect, useRef } from "react";
import Glide from "@glidejs/glide";
import { skills } from "@assets/icons";

const Skills: React.FC = () => {
  const glideRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (glideRef.current) {
      const glide = new Glide(glideRef.current, {
        type: "carousel",
        perView: 5,
        gap: 30,
        autoplay: 3000,
        hoverpause: true,
        breakpoints: {
          1024: {
            perView: 4,
          },
          768: {
            perView: 3,
          },
          480: {
            perView: 2,
          },
        },
      });

      glide.mount();

      return () => {
        glide.destroy();
      };
    }
  }, []);

  return (
    <div className="glide" ref={glideRef}>
      <div className="glide__track" data-glide-el="track">
        <ul className="glide__slides">
          {skills.map((skill, index) => (
            <li key={index} className="glide__slide">
              <div className="flex flex-col items-center">
                <div
                  className="flex items-center justify-center p-8 rounded-3xl shadow-lg transition-transform hover:scale-105 mb-3"
                  style={{ backgroundColor: skill.color }}
                >
                  <i
                    className={`${skill.icon} text-8xl`}
                    style={{ color: "white" }}
                    title={skill.alt || skill.title}
                  />
                </div>
                <span className="text-black font-medium text-xl text-center">
                  {skill.title}
                </span>
              </div>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default Skills;
